#include "problem/elliptic/finite_deformation_mechanics/HyperElastostaticResidual_decl.hpp"
#ifndef PLATOANALYZE_USE_EXPLICIT_INSTANTIATION
#include "problem/elliptic/finite_deformation_mechanics/HyperElastostaticResidual_def.hpp"
#endif
