stages: [build-engine, build-analyze]

variables:
  GIT_SUBMODULE_STRATEGY: normal
  CLEAN_CACHE: "true"
  PLATO_ANALYZE_GPU_OPTIONS: "+amgx+cuda+tacho+enginemesh+esp+geometry+mpmd+python"
  PLATO_ANALYZE_CPU_OPTIONS: "~amgx~cuda+tacho+enginemesh+esp+geometry+mpmd+python"
  PLATO_ENGINE_OPTIONS_FOR_PA: "+esp+expy+geometry+iso+prune+rol+stk~regression~unit_testing"
  THIRD_PARTY_GPU_OPTIONS_COMMON: "^trilinos~mumps+rol~pardiso cuda_arch=70 ^openmpi@4.1.3 ^esp@120Lin"
  THIRD_PARTY_CPU_OPTIONS_COMMON: "^trilinos~mumps+rol~pardiso ^openmpi@4.1.3 ^esp@120Lin"
  THIRD_PARTY_GPU_OPTIONS_FOR_PA: "^amgx cuda_arch=70"
  THIRD_PARTY_CPU_OPTIONS_FOR_PA: ""
  SPACK_DIR_FOR_PA: spack_pa_cache_${CI_PROJECT_ID}

trigger-cpu:
  stage: build-analyze
  variables:
    TRIGGER_PLATO_ANALYZE_OPTIONS: ${PLATO_ANALYZE_CPU_OPTIONS}
    TRIGGER_PLATO_ENGINE_OPTIONS: ${PLATO_ENGINE_OPTIONS_FOR_PA}
    TRIGGER_THIRD_PARTY_OPTIONS_COMMON: ${THIRD_PARTY_CPU_OPTIONS_COMMON}
    TRIGGER_THIRD_PARTY_OPTIONS_FOR_PA: ${THIRD_PARTY_CPU_OPTIONS_FOR_PA}
    TRIGGER_SPACK_DIR: ${SPACK_DIR_FOR_PA}
    CONFIGURATION: "cpu"
  trigger:
    include: ci-pipeline.yml
    strategy: depend
  when: always
  needs: []

trigger-gpu:
  stage: build-analyze
  variables:
    TRIGGER_PLATO_ANALYZE_OPTIONS: ${PLATO_ANALYZE_GPU_OPTIONS}
    TRIGGER_PLATO_ENGINE_OPTIONS: ${PLATO_ENGINE_OPTIONS_FOR_PA}
    TRIGGER_THIRD_PARTY_OPTIONS_COMMON: ${THIRD_PARTY_GPU_OPTIONS_COMMON}
    TRIGGER_THIRD_PARTY_OPTIONS_FOR_PA: ${THIRD_PARTY_GPU_OPTIONS_FOR_PA}
    TRIGGER_SPACK_DIR: ${SPACK_DIR_FOR_PA}
    CONFIGURATION: "gpu"
  trigger:
    include: ci-pipeline.yml
    strategy: depend
  when: always
  needs: []
