set(ANALYZE_BASE_DIR ${CMAKE_CURRENT_SOURCE_DIR})
set(CMAKE_UTIL_DIR ${CMAKE_CURRENT_SOURCE_DIR}/cmake)
set(TEST_TEUCHOS_UNIT_MAIN_INCL ${CMAKE_CURRENT_SOURCE_DIR}/cmake/TeuchosUnitTestMain.cpp)
set(ANALYZE_TEST_DATA_DIR ${CMAKE_CURRENT_SOURCE_DIR}/test_utilities/data)
