include(./cmake/analyze_common_setup.cmake)

add_subdirectory(./core_types)
add_subdirectory(./test_utilities)
add_subdirectory(./utilities)
add_subdirectory(./parsing)
add_subdirectory(./linear_algebra)
add_subdirectory(./element)
add_subdirectory(./simplex)
add_subdirectory(./mesh)
add_subdirectory(./domain)
add_subdirectory(./material)
add_subdirectory(./boundary_conditions)
add_subdirectory(./local_operations)
add_subdirectory(./solver)
add_subdirectory(./problem)
add_subdirectory(./main)
add_subdirectory(./functional)
